# Generated by Django 3.1.7 on 2021-04-04 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='codingsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1824, unique=True)),
                ('language', models.CharField(max_length=1824)),
                ('link', models.CharField(max_length=2848)),
                ('starting_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
